package com.ecopic.entity;
// Generated Oct 18, 2022, 3:29:14 AM by Hibernate Tools 5.6.12.Final

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name ="category", catalog = "ecopic")
@NamedQueries({
	@NamedQuery(name="Category.findAll", query = "SELECT c FROM Category c ORDER BY c.name"),
	@NamedQuery(name="Category.findByName", query = "SELECT c FROM Category c WHERE c.name = :name"),
	@NamedQuery(name="Category.countAll", query = "SELECT Count(*) From Category"),
})
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String name;

	public Category() {
	}

	public Category(Integer id, String name) {
		this(name);
		this.categoryId = id;
	}
	
	public Category(String name) {
		this.name = name;
	}

	public Category(String name, Set<?> pictures) {
		this.name = name;
	}
	@Column(name="category_id")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
