package com.ecopic.entity;
// Generated Oct 30, 2022, 1:32:48 PM by Hibernate Tools 5.2.13.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OderDetail generated by hbm2java
 */
@Entity
@Table(name = "oder_detail", catalog = "ecopic")
public class OderDetail implements java.io.Serializable {

	private OderDetailId id;
	private Picture picture;
	private PictureOder pictureOder;

	public OderDetail() {
	}

	public OderDetail(OderDetailId id) {
		this.id = id;
	}

	public OderDetail(OderDetailId id, Picture picture, PictureOder pictureOder) {
		this.id = id;
		this.picture = picture;
		this.pictureOder = pictureOder;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "oderId", column = @Column(name = "oder_id")),
			@AttributeOverride(name = "pictureId", column = @Column(name = "picture_id")),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", nullable = false)),
			@AttributeOverride(name = "subtotal", column = @Column(name = "subtotal", nullable = false, precision = 12, scale = 0)) })
	public OderDetailId getId() {
		return this.id;
	}

	public void setId(OderDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "picture_id", insertable = false, updatable = false)
	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oder_id", insertable = false, updatable = false)
	public PictureOder getPictureOder() {
		return this.pictureOder;
	}

	public void setPictureOder(PictureOder pictureOder) {
		this.pictureOder = pictureOder;
	}

}
