package com.ecopic.entity;
// Generated Oct 18, 2022, 3:29:14 AM by Hibernate Tools 5.6.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PictureOder generated by hbm2java
 */
@SuppressWarnings("serial")

public class PictureOder implements java.io.Serializable {

	private int oderId;
	private Customer customer;
	private Date oderDate;
	private String shippingAddress;
	private String recipientName;
	private String recipientPhone;
	private String paymentMethod;
	private float total;
	private String status;
	private Set oderDetails = new HashSet(0);

	public PictureOder() {
	}

	public PictureOder(int oderId, Customer customer, Date oderDate, String shippingAddress, String recipientName,
			String recipientPhone, String paymentMethod, float total, String status) {
		this.oderId = oderId;
		this.customer = customer;
		this.oderDate = oderDate;
		this.shippingAddress = shippingAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.paymentMethod = paymentMethod;
		this.total = total;
		this.status = status;
	}

	public PictureOder(int oderId, Customer customer, Date oderDate, String shippingAddress, String recipientName,
			String recipientPhone, String paymentMethod, float total, String status, Set oderDetails) {
		this.oderId = oderId;
		this.customer = customer;
		this.oderDate = oderDate;
		this.shippingAddress = shippingAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.paymentMethod = paymentMethod;
		this.total = total;
		this.status = status;
		this.oderDetails = oderDetails;
	}

	public int getOderId() {
		return this.oderId;
	}

	public void setOderId(int oderId) {
		this.oderId = oderId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getOderDate() {
		return this.oderDate;
	}

	public void setOderDate(Date oderDate) {
		this.oderDate = oderDate;
	}

	public String getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	public String getRecipientName() {
		return this.recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	public String getRecipientPhone() {
		return this.recipientPhone;
	}

	public void setRecipientPhone(String recipientPhone) {
		this.recipientPhone = recipientPhone;
	}

	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getOderDetails() {
		return this.oderDetails;
	}

	public void setOderDetails(Set oderDetails) {
		this.oderDetails = oderDetails;
	}

}
